#ifndef INDEX_H
#define INDEX_H
const char *index_html="<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<html>"
"<body>"
"<center>"
"<table>"
"<tr><td><label>SSID:</label></td><td><input id='ssid-input'></td></tr>"
"<tr><td><label>PASS:</label></td><td><input id='pass-input' type='password'></td></tr>"
"</table>"
"<p>"
"<button id='c-btn'>Connect</button>"
"</center>"
"</body>"
"<script>"
"let ssid_field = document.getElementById('ssid-input');"
"let pass_field = document.getElementById('pass-input');"
"document.getElementById('c-btn').addEventListener('click',()=>{"
"let ssid = ssid_field.value;"
"let pass = pass_field.value;"
"if(ssid && pass){"
"let xhr = new XMLHttpRequest();"
"xhr.open('POST','/post');"
"xhr.send(ssid + '-' + pass);"
"}"
"});"
"</script>"
"</html>";
#endif
